# config/meta.yml

meta_product_name: "teamup∞™"
meta_title: "teamup∞™ - Creating high performing teams"
meta_description: "We believe that leaders and teams can always get better. Better Teams. Better Times. Striving for better is both healthy and something you can habituate. So teamup∞™ offers a range of solutions built on neuroscience designed to accelerate individual and team performance."
meta_image: "magazine.jpg" # should exist in `app/assets/images/` TO BE UPDATED
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
